Add "how to install" hint
eclipse-tractusx/tractus-x-release pull request #11
Opened 2023-04-03 11:10 UTC by Siegfriedk

Missing information discovered through 'download link' requirement from ef

2023-04-03 12:08 UTC, almadigabor requested changes

2023-04-03 12:08 UTC, almadigabor commented on README.md
> +All components are based on [Helm](https://helm.sh/) Charts. To find the right versions of them, see our overarching [CHANGELOG.md](CHANGELOG.md) for versions which have been tested and released toge
```suggestion
All components are based on [Helm](https://helm.sh/) Charts. To find the right versions of them, see our overarching [CHANGELOG.md](CHANGELOG.md) for versions which have been tested and released together and are compatible with each other. All components have their own installation guides.
```

2023-04-04 05:44 UTC, almadigabor approved these changes

2023-04-04 06:23 UTC, SebastianBezold approved these changes

2023-04-04 07:36 UTC, merged